// get user resume details
export const GET_USER_RESUME_DETAILS_START = 'GET_USER_RESUME_DETAILS_START';
export const GET_USER_RESUME_DETAILS_SUCCESS = 'GET_USER_RESUME_DETAILS_SUCCESS';
export const GET_USER_RESUME_DETAILS_FAIL = 'GET_USER_RESUME_DETAILS_FAIL';

// upload user reumse for review
export const UPLOAD_USER_RESUME_DETAILS_START = 'UPLOAD_USER_RESUME_DETAILS_START';
export const UPLOAD_USER_RESUME_DETAILS_SUCCESS = 'UPLOAD_USER_RESUME_DETAILS_SUCCESS';
export const UPLOAD_USER_RESUME_DETAILS_FAIL = 'UPLOAD_USER_RESUME_DETAILS_FAIL';

// get user pricing details
export const GET_USER_RESUME_PRICING_START = 'GET_USER_RESUME_PRICING_START';
export const GET_USER_RESUME_PRICING_SUCCESS = 'GET_USER_RESUME_PRICING_SUCCESS';
export const GET_USER_RESUME_PRICING_FAIL = 'GET_USER_RESUME_PRICING_FAIL';

// get users trends statistics
export const GET_USER_TRENDS_STAT_START = 'GET_USER_TRENDS_STAT_START';
export const GET_USER_TRENDS_STAT_SUCCESS = 'GET_USER_TRENDS_STAT_SUCCESS';
export const GET_USER_TRENDS_STAT_FAIL = 'GET_USER_TRENDS_STAT_FAIL';

// user resume pricing clickeed
export const POST_USER_RESUME_PRICING_START = 'POST_USER_RESUME_PRICING_START';
export const POST_USER_RESUME_PRICING_SUCCESS = 'POST_USER_RESUME_PRICING_SUCCESS';
export const POST_USER_RESUME_PRICING_FAIL = 'POST_USER_RESUME_PRICING_FAIL';

// clearing network info details for the particular user
export const CLEAR_USER_ALLRESUME_DETAILS = 'CLEAR_USER_RESET_DETAILS';

// resume download user
export const USER_RESUME_DONWLOAD_START = 'USER_RESUME_DONWLOAD_START';
export const USER_RESUME_DONWLOAD_FAIL = 'USER_RESUME_DONWLOAD_FAIL';
export const USER_RESUME_DONWLOAD_LOADING = 'USER_RESUME_DONWLOAD_LOADING';

