// user login authentication (sign in page)
export const FETCH_PROFILE_USER_DETAILS_START = 'FETCH_PROFILE_USER_DETAILS_START';
export const FETCH_PROFILE_USER_DETAILS_SUCCESS = 'FETCH_PROFILE_USER_DETAILS_SUCCESS';
export const FETCH_PROFILE_USER_DETAILS_FAIL = 'FETCH_PROFILE_USER_DETAILS_FAIL';

// user login authentication (sign in page)
export const UPDATE_PROFILE_USER_RESUME_START = 'UPDATE_PROFILE_USER_RESUME_START';
export const UPDATE_PROFILE_USER_RESUME_SUCCESS = 'UPDATE_PROFILE_USER_RESUME_SUCCESS';
export const UPDATE_PROFILE_USER_RESUME_FAIL = 'UPDATE_PROFILE_USER_RESUME_FAIL';

// user login authentication (sign in page)
export const UPDATE_PROFILE_USER_SUMMARY_START = 'UPDATE_PROFILE_USER_SUMMARY_START';
export const UPDATE_PROFILE_USER_SUMMARY_SUCCESS = 'UPDATE_PROFILE_USER_SUMMARY_SUCCESS';
export const UPDATE_PROFILE_USER_SUMMARY_FAIL = 'UPDATE_PROFILE_USER_SUMMARY_FAIL';

// user login authentication (sign in page)
export const UPDATE_PROFILE_USER_ECE_START = 'UPDATE_PROFILE_USER_ECE_START';
export const UPDATE_PROFILE_USER_ECE_SUCCESS = 'UPDATE_PROFILE_USER_ECE_SUCCESS';
export const UPDATE_PROFILE_USER_ECE_FAIL = 'UPDATE_PROFILE_USER_ECE_FAIL';

// user login authentication (sign in page)
export const ADD_NEW_PROFILE_USER_ECE_START = 'ADD_NEW_PROFILE_USER_ECE_START';
export const ADD_NEW_PROFILE_USER_ECE_SUCCESS = 'ADD_NEW_PROFILE_USER_ECE_SUCCESS';
export const ADD_NEW_PROFILE_USER_ECE_FAIL = 'ADD_NEW_PROFILE_USER_ECE_FAIL';

// user login authentication (sign in page)
export const UPDATE_PROFILE_USER_SKILLS_START = 'UPDATE_PROFILE_USER_SKILLS_START';
export const UPDATE_PROFILE_USER_SKILLS_SUCCESS = 'UPDATE_PROFILE_USER_SKILLS_SUCCESS';
export const UPDATE_PROFILE_USER_SKILLS_FAIL = 'UPDATE_PROFILE_USER_SKILLS_FAIL';

// user login authentication (sign in page)
export const UPDATE_PROFILE_USER_OTHER_DETAILS_START = 'UPDATE_PROFILE_USER_OTHER_DETAILS_START';
export const UPDATE_PROFILE_USER_OTHER_DETAILS_SUCCESS = 'UPDATE_PROFILE_USER_OTHER_DETAILS_SUCCESS';
export const UPDATE_PROFILE_USER_OTHER_DETAILS_FAIL = 'UPDATE_PROFILE_USER_OTHER_DETAILS_FAIL';

// clearing network info details for the particular user
export const CLEAR_PROFILE_USER_DETAILS = 'CLEAR_PROFILE_USER_DETAILS';

