// user login authentication (sign in page)
export const JOB_INFO_FETCH_DETAILS_START = 'JOB_INFO_FETCH_DETAILS_START';
export const JOB_INFO_FETCH_DETAILS_SUCCESS = 'JOB_INFO_FETCH_DETAILS_SUCCESS';
export const JOB_INFO_FETCH_DETAILS_FAIL = 'JOB_INFO_FETCH_DETAILS_FAIL';

// job profile click (to update the count)
export const JOB_PROFILE_CLICK_START = 'JOB_PROFILE_CLICK_START';
export const JOB_PROFILE_CLICK_SUCCESS = 'JOB_PROFILE_CLICK_SUCCESS';
export const JOB_PROFILE_CLICK_FAIL = 'JOB_PROFILE_CLICK_FAIL';

// job profile QUESTIONS
export const JOB_PROFILE_FETCH_QUESTIONS_START = 'JOB_PROFILE_FETCH_QUESTIONS_START';
export const JOB_PROFILE_FETCH_QUESTIONS_SUCCESS = 'JOB_PROFILE_FETCH_QUESTIONS_SUCCESS';
export const JOB_PROFILE_FETCH_QUESTIONS_FAIL = 'JOB_PROFILE_FETCH_QUESTIONS_FAIL';

// job profile submit to the end client
export const JOB_PROFILE_SUBMIT_START = 'JOB_PROFILE_SUBMIT_START';
export const JOB_PROFILE_SUBMIT_SUCCESS = 'JOB_PROFILE_SUBMIT_SUCCESS';
export const JOB_PROFILE_SUBMIT_FAIL = 'JOB_PROFILE_SUBMIT_FAIL';

// clearing JOB info details for the particular user
export const CLEAR_JOB_INFO_DETAILS = 'CLEAR_JOB_INFO_DETAILS';

