# Generated by Django 4.2.3 on 2023-11-07 03:59

import backend.models.ResumeModel
import backend.models.UserModel
from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('USR_HLF', models.IntegerField(default=121)),
                ('USR_EMAIL_VERIFIED', models.BooleanField(default=False)),
                ('USR_MESSAGE_REQUEST', models.IntegerField(blank=True, null=True)),
                ('USR_PHONE', models.CharField(blank=True, max_length=12, null=True)),
                ('USR_POSITION_TITLE', models.CharField(blank=True, max_length=255, null=True)),
                ('USR_DATEOFBIRTH', models.DateField(blank=True, null=True)),
                ('USR_GENDER', models.IntegerField(default=-1)),
                ('USR_LOCATION_REQUEST', models.BooleanField(default=False)),
                ('USR_JOB_POST_LIMIT', models.IntegerField(default=2)),
                ('USR_GUID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('USR_RESUME_SUB', models.BooleanField(default=False)),
                ('USR_JOB_CHECK', models.BooleanField(default=True)),
                ('USR_NEWS_SUBSCRIPTION', models.BooleanField(default=False)),
                ('USR_RESUME', models.FileField(upload_to=backend.models.UserModel.user_resume_path)),
                ('USR_WEBSITE', models.CharField(blank=True, max_length=50, null=True)),
                ('USR_OTHER_DETAILS', models.TextField(blank=True, null=True)),
                ('USR_TIMEZONE', models.CharField(blank=True, max_length=100, null=True)),
                ('TOKEN', models.TextField(blank=True, null=True)),
                ('USR_OTHER_PREFERENCE', models.TextField(blank=True, null=True)),
                ('USR_JOB_PREFERENCES', models.CharField(blank=True, max_length=100, null=True)),
                ('USR_ACTIVE', models.BooleanField(default=False, verbose_name='active')),
                ('USR_MONGO_STORED', models.BooleanField(default=False, verbose_name='mongo stored')),
                ('USR_NOTES', models.TextField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'tbluser',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('CT_ID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('CT_EMAIL', models.CharField(max_length=500)),
                ('CT_PHONE', models.CharField(blank=True, max_length=14, null=True)),
                ('CT_WEBSITE', models.CharField(blank=True, max_length=500, null=True)),
                ('CT_DESCRIPTION', models.TextField(blank=True, null=True)),
                ('CT_FIRST_NAME', models.CharField(max_length=500)),
                ('CT_LAST_NAME', models.CharField(max_length=100)),
                ('CT_CREATED', models.DateTimeField(auto_now_add=True)),
                ('CT_TICKET_NUMBER', models.CharField(max_length=12)),
                ('CT_TICKET_CLOSE', models.BooleanField(default=False, verbose_name='Status')),
                ('CT_TICKET_CLOSE_DATE', models.DateTimeField(blank=True, null=True)),
                ('CT_ORGANIZATION', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'tblcontact',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('DEPARTMENT_ID', models.AutoField(auto_created=True, default=500, primary_key=True, serialize=False)),
                ('DEPARTMENT_NAME', models.CharField(max_length=150)),
                ('CREATED_DATE', models.DateTimeField(auto_now_add=True)),
                ('CREATED_BY', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbldepartment',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('RS_ID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('RS_RESUME', models.FileField(upload_to=backend.models.ResumeModel.user_resume_path)),
                ('RS_CREATED', models.DateTimeField(auto_now_add=True)),
                ('RS_REVIEW', models.BooleanField(default=False, verbose_name='Status')),
                ('RS_REVIEW_COUNT', models.IntegerField(default=1)),
                ('RS_NOTES', models.TextField(blank=True, null=True)),
                ('RS_INITIAL_REVIEW', models.BooleanField(default=False, verbose_name='initial review')),
                ('RS_UPDATED', models.DateTimeField(blank=True, null=True)),
                ('RS_REVIEW_COMPLETED', models.BooleanField(default=False, verbose_name='review completed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tblresume',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('USR_EXP_ID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('USR_EXP_POSITION', models.CharField(max_length=150)),
                ('USR_EXP_SKILLS', models.TextField(blank=True, null=True)),
                ('USR_EXP_DESCRIPTION', models.TextField(blank=True, null=True)),
                ('USR_EXP_START', models.CharField(blank=True, max_length=50, null=True)),
                ('USR_EXP_END', models.CharField(blank=True, max_length=50, null=True)),
                ('USR_EXP_COUNTRY', models.IntegerField()),
                ('USR_EXP_STATE', models.IntegerField()),
                ('USR_EXP_POSTAL', models.CharField(blank=True, max_length=10, null=True)),
                ('USR_EXP_TYPE', models.IntegerField(default=121)),
                ('USR_CREATED', models.DateField(auto_now_add=True)),
                ('USR_EXP_DEPARTMENT', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbluser_experience',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('USR_EDU_ID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('USR_EDU_COLLEGE', models.CharField(max_length=255)),
                ('USR_EDU_COURSE_TYPE', models.CharField(blank=True, max_length=150, null=True)),
                ('USR_EDU_START_DATE', models.CharField(blank=True, max_length=50, null=True)),
                ('USR_EDU_END_DATE', models.CharField(blank=True, max_length=50, null=True)),
                ('USR_EDU_DESCRIPTION', models.TextField(blank=True, null=True)),
                ('USR_EDU_COURSE_NAME', models.CharField(max_length=255)),
                ('USR_EDU_LOCATION', models.CharField(blank=True, max_length=155, null=True)),
                ('USR_EDU_CREATED', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbluser_education',
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('USR_CERT_ID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('USR_CERT_NAME', models.CharField(max_length=300)),
                ('USR_CERT_LICENSE', models.CharField(blank=True, max_length=255, null=True)),
                ('USR_CERT_ISSUE', models.CharField(blank=True, max_length=50, null=True)),
                ('USR_CERT_EXPIRY', models.CharField(blank=True, max_length=50, null=True)),
                ('USR_CERT_DESCRIPTION', models.TextField(blank=True, null=True)),
                ('USR_CREATED', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbluser_certification',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('USR_ADDRESS_ID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('USR_ADDRESS', models.CharField(blank=True, max_length=400, null=True)),
                ('USR_UNIT', models.CharField(max_length=20)),
                ('USR_CITY', models.IntegerField(blank=True, null=True)),
                ('USR_STATE', models.IntegerField(blank=True, null=True)),
                ('USR_COUNTRY', models.IntegerField()),
                ('USR_POSTAL', models.CharField(blank=True, max_length=10, null=True)),
                ('USR_ADDRESS_TYPE', models.IntegerField(blank=True, null=True)),
                ('CREATED_DATE', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbladdress',
            },
        ),
    ]
