export const FETCH_USER_BLOG_DETAILS_START = 'FETCH_USER_BLOG_DETAILS_START';
export const FETCH_USER_BLOG_DETAILS_SUCCESS = 'FETCH_USER_BLOG_DETAILS_SUCCESS';
export const FETCH_USER_BLOG_DETAILS_FAIL = 'FETCH_USER_BLOG_DETAILS_FAIL';
