// user registration authentication
export const USER_REGISTER_START = 'USER_REGISTER_START';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const CLEAR_ALL_REGISTRATION_DETAILS='CLEAR_ALL_REGISTRATION_DETAILS';